name: Generate Snake

on:
  schedule:                     # Runs automatically twice a day
    - cron: "0 */12 * * *"
  workflow_dispatch:             # Allows manual run from the "Actions" tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: CourtneyBritney        # ðŸ‘ˆ Your GitHub username
          outputs: dist/snake.svg

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output                    # ðŸ‘ˆ Branch where the SVG will be stored
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHubâ€™s built-in auth token
